name: train_toy_data_model
functions:
- url: https://raw.githubusercontent.com/yjb-ds/functions-refac/master/get_toy_data/function.yaml
  name: get_toy_data
- url: https://raw.githubusercontent.com/yjb-ds/functions-refac/master/describe/function.yaml
  name: describe
- url: https://raw.githubusercontent.com/yjb-ds/functions-refac/master/get_model_config/function.yaml
  name: get_model_config
- url: https://raw.githubusercontent.com/yjb-ds/functions-refac/master/sklearn_classifier/function.yaml
  name: train_model
workflows:
- name: main
  code: workflow.py
