name: train_xgb_classifier
functions:
- url: https://raw.githubusercontent.com/mlrun/functions/master/load_dataset/function.yaml
  name: get_data
- url: https://raw.githubusercontent.com/mlrun/functions/master/describe/function.yaml
  name: summary
- url: https://raw.githubusercontent.com/mlrun/functions/master/sklearn_classifier/function.yaml
  name: train
- url: https://raw.githubusercontent.com/mlrun/functions/master/test_classifier/function.yaml
  name: test
- url: https://raw.githubusercontent.com/mlrun/functions/master/serving/model_server.ipynb
  name: server
workflows:
- name: main
  code: workflow.py
artifacts: []
